import {
  AirplaneFillIcon,
  AirplaneIcon,
  AlignBottomFillIcon,
  AlignBottomIcon,
  AlignCenterFillIcon,
  AlignCenterIcon,
  AlignLeftFillIcon,
  AlignLeftIcon,
  AlignMiddleFillIcon,
  AlignMiddleIcon,
  AlignRightFillIcon,
  AlignRightIcon,
  AlignTopFillIcon,
  AlignTopIcon,
  AllergensFillIcon,
  AllergensIcon,
  AngleIcon,
  AngleRulerCircleFillIcon,
  AngleRulerCircleIcon,
  AngleRulerTriangleFillIcon,
  AngleRulerTriangleIcon,
  ArchiveFillIcon,
  ArchiveIcon,
  AreaChartFillIcon,
  AreaChartIcon,
  ArrowCirclepathIcon,
  ArrowDownIcon,
  ArrowDownRightIcon,
  ArrowForwardFillIcon,
  ArrowForwardIcon,
  ArrowLeftIcon,
  ArrowRedoIcon,
  ArrowRightIcon,
  ArrowRightLeftIcon,
  ArrowUndoIcon,
  ArrowUpIcon,
  ArrowsCirclepathIcon,
  ArrowsSquarepathIcon,
  ArrowsUpDownIcon,
  BabyWrappedFillIcon,
  BabyWrappedIcon,
  BackpackFillIcon,
  BackpackIcon,
  BackwardFillIcon,
  BackwardIcon,
  BacteriaFillIcon,
  BacteriaIcon,
  BagdeFillIcon,
  BagdeIcon,
  BaggageFillIcon,
  BaggageIcon,
  BandageFillIcon,
  BandageIcon,
  BankNoteFillIcon,
  BankNoteIcon,
  BarChartFillIcon,
  BarChartIcon,
  BedFillIcon,
  BedIcon,
  BellDotFillIcon,
  BellDotIcon,
  BellFillIcon,
  BellIcon,
  BicycleIcon,
  BoatFillIcon,
  BoatIcon,
  BoneBrokenIcon,
  BoneFillIcon,
  BoneIcon,
  BookFillIcon,
  BookIcon,
  BookmarkDashIcon,
  BookmarkFillIcon,
  BookmarkIcon,
  BooksFillIcon,
  BooksIcon,
  BowlFillIcon,
  BowlIcon,
  BrailleFillIcon,
  BrailleIcon,
  BranchingIcon,
  BriefcaseClockFillIcon,
  BriefcaseClockIcon,
  BriefcaseFillIcon,
  BriefcaseIcon,
  BroadcastIcon,
  BroadcastMinusCircleFillIcon,
  BroadcastMinusCircleIcon,
  BroadcastPlusCircleFillIcon,
  BroadcastPlusCircleIcon,
  BubbleChartFillIcon,
  BubbleChartIcon,
  BucketFillIcon,
  BucketIcon,
  BucketMopFillIcon,
  BucketMopIcon,
  BugFillIcon,
  BugIcon,
  Buildings2FillIcon,
  Buildings2Icon,
  Buildings3FillIcon,
  Buildings3Icon,
  BulletListIcon,
  BusFillIcon,
  BusIcon,
  CalculatorFillIcon,
  CalculatorIcon,
  CalendarFillIcon,
  CalendarIcon,
  CameraFillIcon,
  CameraIcon,
  CameraTriangleFillIcon,
  CameraTriangleIcon,
  CandleFillIcon,
  CandleIcon,
  CaptionsFillIcon,
  CaptionsIcon,
  CarFillIcon,
  CarIcon,
  CardFillIcon,
  CardIcon,
  CaretDownCircleFillIcon,
  CaretDownCircleIcon,
  CaretDownFillIcon,
  CaretDownIcon,
  CaretLeftCircleFillIcon,
  CaretLeftCircleIcon,
  CaretLeftFillIcon,
  CaretLeftIcon,
  CaretLeftRightFillIcon,
  CaretLeftRightIcon,
  CaretRightCircleFillIcon,
  CaretRightCircleIcon,
  CaretRightFillIcon,
  CaretRightIcon,
  CaretUpCircleFillIcon,
  CaretUpCircleIcon,
  CaretUpDownFillIcon,
  CaretUpDownFilledDownIcon,
  CaretUpDownFilledUpIcon,
  CaretUpDownIcon,
  CaretUpFillIcon,
  CaretUpIcon,
  ChangingRoomFillIcon,
  ChangingRoomIcon,
  Chat2FillIcon,
  Chat2Icon,
  ChatCheckmarkFillIcon,
  ChatCheckmarkIcon,
  ChatElipsisFillIcon,
  ChatElipsisIcon,
  ChatExclamationmarkFillIcon,
  ChatExclamationmarkIcon,
  ChatFillIcon,
  ChatIcon,
  CheckmarkCircleFillIcon,
  CheckmarkCircleIcon,
  CheckmarkIcon,
  ChefHatFillIcon,
  ChefHatIcon,
  ChevronDownCircleFillIcon,
  ChevronDownCircleIcon,
  ChevronDownDoubleCircleFillIcon,
  ChevronDownDoubleCircleIcon,
  ChevronDownDoubleIcon,
  ChevronDownIcon,
  ChevronDownUpIcon,
  ChevronLeftCircleFillIcon,
  ChevronLeftCircleIcon,
  ChevronLeftDoubleCircleFillIcon,
  ChevronLeftDoubleCircleIcon,
  ChevronLeftDoubleIcon,
  ChevronLeftFirstCircleFillIcon,
  ChevronLeftFirstCircleIcon,
  ChevronLeftFirstIcon,
  ChevronLeftIcon,
  ChevronRightCircleFillIcon,
  ChevronRightCircleIcon,
  ChevronRightDoubleCircleFillIcon,
  ChevronRightDoubleCircleIcon,
  ChevronRightDoubleIcon,
  ChevronRightIcon,
  ChevronRightLastCircleFillIcon,
  ChevronRightLastCircleIcon,
  ChevronRightLastIcon,
  ChevronUpCircleFillIcon,
  ChevronUpCircleIcon,
  ChevronUpDoubleCircleFillIcon,
  ChevronUpDoubleCircleIcon,
  ChevronUpDoubleIcon,
  ChevronUpDownIcon,
  ChevronUpIcon,
  ChildEyesFillIcon,
  ChildEyesIcon,
  ChildHairEyesFillIcon,
  ChildHairEyesIcon,
  CigaretteFillIcon,
  CigaretteIcon,
  CircleBrokenIcon,
  CircleFillIcon,
  CircleIcon,
  CircleSlashFillIcon,
  CircleSlashIcon,
  ClipboardCheckmarkFillIcon,
  ClipboardCheckmarkIcon,
  ClipboardFillIcon,
  ClipboardIcon,
  ClipboardLinkFillIcon,
  ClipboardLinkIcon,
  ClipboardXMarkFillIcon,
  ClipboardXMarkIcon,
  ClockDashedIcon,
  ClockFillIcon,
  ClockIcon,
  ClothingHangerFillIcon,
  ClothingHangerIcon,
  CloudDownFillIcon,
  CloudDownIcon,
  CloudFillIcon,
  CloudIcon,
  CloudSlashFillIcon,
  CloudSlashIcon,
  CloudUpFillIcon,
  CloudUpIcon,
  CodeIcon,
  CoffeeFillIcon,
  CoffeeIcon,
  CogFillIcon,
  CogIcon,
  CogRotationFillIcon,
  CogRotationIcon,
  Combifridge1FillIcon,
  Combifridge1Icon,
  Combifridge2FillIcon,
  Combifridge2Icon,
  CompassFillIcon,
  CompassIcon,
  ComponentFillIcon,
  ComponentIcon,
  CurrencyExchangeIcon,
  CutleryFillIcon,
  CutleryIcon,
  DatabaseFillIcon,
  DatabaseIcon,
  Density1FillIcon,
  Density1Icon,
  Density2FillIcon,
  Density2Icon,
  Density3Icon,
  DiamondFillIcon,
  DiamondIcon,
  DishwasherFillIcon,
  DishwasherIcon,
  DivideIcon,
  DocPencilFillIcon,
  DocPencilIcon,
  DogFillIcon,
  DogHarnessFillIcon,
  DogHarnessIcon,
  DogIcon,
  DonutChartFillIcon,
  DonutChartIcon,
  DonutsFillIcon,
  DonutsIcon,
  DoorFillIcon,
  DoorIcon,
  DoorOpenFillIcon,
  DoorOpenIcon,
  DownloadIcon,
  DragHorizontalIcon,
  DragVerticalIcon,
  EarFillIcon,
  EarIcon,
  EarSlashFillIcon,
  EarSlashIcon,
  EarSoundwavesFillIcon,
  EarSoundwavesIcon,
  EarthFillIcon,
  EarthIcon,
  ElevatorFillIcon,
  ElevatorIcon,
  EnterIcon,
  EnvelopeClosedFillIcon,
  EnvelopeClosedIcon,
  EnvelopeOpenFillIcon,
  EnvelopeOpenIcon,
  EqualsIcon,
  EraserFillIcon,
  EraserIcon,
  EscalatorIcon,
  EthernetIcon,
  ExclamationmarkIcon,
  ExclamationmarkTriangleFillIcon,
  ExclamationmarkTriangleIcon,
  ExpandIcon,
  ExternalLinkFillIcon,
  ExternalLinkIcon,
  EyeClosedIcon,
  EyeFillIcon,
  EyeIcon,
  EyeObfuscatedFillIcon,
  EyeObfuscatedIcon,
  EyeSlashFillIcon,
  EyeSlashIcon,
  EyeWithPupilFillIcon,
  EyeWithPupilIcon,
  FaceCryFillIcon,
  FaceCryIcon,
  FaceFillIcon,
  FaceFrownFillIcon,
  FaceFrownIcon,
  FaceIcon,
  FaceLaughFillIcon,
  FaceLaughIcon,
  FaceSmileFillIcon,
  FaceSmileIcon,
  FeedingBottleFillIcon,
  FeedingBottleIcon,
  FigureChildFillIcon,
  FigureChildIcon,
  FigureCombinationFillIcon,
  FigureCombinationIcon,
  FigureFillIcon,
  FigureIcon,
  FigureInwardFillIcon,
  FigureInwardIcon,
  FigureOutwardFillIcon,
  FigureOutwardIcon,
  FileCheckmarkFillIcon,
  FileCheckmarkIcon,
  FileCodeFillIcon,
  FileCodeIcon,
  FileCsvFillIcon,
  FileCsvIcon,
  FileExcelFillIcon,
  FileExcelIcon,
  FileExportFillIcon,
  FileExportIcon,
  FileFillIcon,
  FileIcon,
  FileImageFillIcon,
  FileImageIcon,
  FileImportFillIcon,
  FileImportIcon,
  FileJsonFillIcon,
  FileJsonIcon,
  FileLoadingFillIcon,
  FileLoadingIcon,
  FileParagraphFillIcon,
  FileParagraphIcon,
  FilePdfFillIcon,
  FilePdfIcon,
  FilePlusFillIcon,
  FilePlusIcon,
  FileResetFillIcon,
  FileResetIcon,
  FileSearchFillIcon,
  FileSearchIcon,
  FileShredderFillIcon,
  FileShredderIcon,
  FileTextFillIcon,
  FileTextIcon,
  FileWordFillIcon,
  FileWordIcon,
  FileXMarkFillIcon,
  FileXMarkIcon,
  FilesFillIcon,
  FilesIcon,
  FilterIcon,
  FingerButtonFillIcon,
  FingerButtonIcon,
  FingerMobileFillIcon,
  FingerMobileIcon,
  FirstAidFillIcon,
  FirstAidIcon,
  FirstAidKitFillIcon,
  FirstAidKitIcon,
  FlagCrossFillIcon,
  FlagCrossIcon,
  FloppydiskFillIcon,
  FloppydiskIcon,
  FlowerFillIcon,
  FlowerIcon,
  FlowerPensionFillIcon,
  FlowerPensionIcon,
  FlowerPetalFallingFillIcon,
  FlowerPetalFallingIcon,
  FlowerPetalsFillIcon,
  FlowerPetalsIcon,
  FolderFileFillIcon,
  FolderFileIcon,
  FolderFillIcon,
  FolderIcon,
  FolderMinusFillIcon,
  FolderMinusIcon,
  FolderPlusFillIcon,
  FolderPlusIcon,
  ForkFillIcon,
  ForkIcon,
  ForwardFillIcon,
  ForwardIcon,
  FreezerFillIcon,
  FreezerIcon,
  FunnelFillIcon,
  FunnelIcon,
  GavelFillIcon,
  GavelIcon,
  GavelSoundBlockFillIcon,
  GavelSoundBlockIcon,
  GlassFillIcon,
  GlassIcon,
  GlassesFillIcon,
  GlassesIcon,
  GlobeFillIcon,
  GlobeIcon,
  GlobeSlashFillIcon,
  GlobeSlashIcon,
  HandBandageFillIcon,
  HandBandageIcon,
  HandFingerFillIcon,
  HandFingerIcon,
  HandHeartFillIcon,
  HandHeartIcon,
  HandKnotFilledIcon,
  HandKnotIcon,
  HandShakeHeartFillIcon,
  HandShakeHeartIcon,
  HandshakeFillIcon,
  HandshakeIcon,
  HangerIcon,
  HardHatFillIcon,
  HardHatIcon,
  HashtagIcon,
  HatSchoolFillIcon,
  HatSchoolIcon,
  HddDownFillIcon,
  HddDownIcon,
  HddUpFillIcon,
  HddUpIcon,
  HeadCloudFillIcon,
  HeadCloudIcon,
  HeadFillIcon,
  HeadHeartFillIcon,
  HeadHeartIcon,
  HeadIcon,
  HearingLoopFillIcon,
  HearingLoopIcon,
  HearingLoopRadioFillIcon,
  HearingLoopRadioIcon,
  HeartBrokenFillIcon,
  HeartBrokenIcon,
  HeartFillIcon,
  HeartIcon,
  HexagonGridFillIcon,
  HexagonGridIcon,
  HikingTrailSignFillIcon,
  HikingTrailSignIcon,
  HospitalFillIcon,
  HospitalIcon,
  HourglassBottomFilledIcon,
  HourglassIcon,
  HourglassTopFilledIcon,
  HouseFillIcon,
  HouseHeartFillIcon,
  HouseHeartIcon,
  HouseIcon,
  ImageFillIcon,
  ImageIcon,
  InboxDownFillIcon,
  InboxDownIcon,
  InboxFillIcon,
  InboxIcon,
  InboxUpFillIcon,
  InboxUpIcon,
  InformationIcon,
  InformationSquareFillIcon,
  InformationSquareIcon,
  IvFluidBagFillIcon,
  IvFluidBagIcon,
  KeyHorizontalFillIcon,
  KeyHorizontalIcon,
  KeyVerticalFillIcon,
  KeyVerticalIcon,
  KnifeFillIcon,
  KnifeIcon,
  KronerIcon,
  LanguageIcon,
  LaptopFillIcon,
  LaptopIcon,
  LaptopTriangleFillIcon,
  LaptopTriangleIcon,
  LayerMinusFillIcon,
  LayerMinusIcon,
  LayersFillIcon,
  LayersIcon,
  LayersPlusFillIcon,
  LayersPlusIcon,
  LeaveIcon,
  LightBulbFillIcon,
  LightBulbIcon,
  LightningFillIcon,
  LightningIcon,
  LineGraphDotIcon,
  LineGraphIcon,
  LineGraphStackedIcon,
  LinkBrokenIcon,
  LinkIcon,
  LocationPinFillIcon,
  LocationPinIcon,
  MagnifyingGlassFillIcon,
  MagnifyingGlassIcon,
  MeasuringTapeFillIcon,
  MeasuringTapeIcon,
  MedicineBottleFillIcon,
  MedicineBottleIcon,
  MeetingLargeFillIcon,
  MeetingLargeIcon,
  MeetingSmallFillIcon,
  MeetingSmallIcon,
  MegaphoneFillIcon,
  MegaphoneIcon,
  MegaphoneSpeakingFillIcon,
  MegaphoneSpeakingIcon,
  MenuElipsisHorizontalCircleFillIcon,
  MenuElipsisHorizontalCircleIcon,
  MenuElipsisHorizontalIcon,
  MenuElipsisHorizontalSquareFillIcon,
  MenuElipsisHorizontalSquareIcon,
  MenuElipsisVerticalCircleFillIcon,
  MenuElipsisVerticalCircleIcon,
  MenuElipsisVerticalIcon,
  MenuElipsisVerticalSquareFillIcon,
  MenuElipsisVerticalSquareIcon,
  MenuGridIcon,
  MenuHamburgerIcon,
  MicrobeFillIcon,
  MicrobeIcon,
  MicrophoneFillIcon,
  MicrophoneIcon,
  MicrophoneSlashFillIcon,
  MicrophoneSlashIcon,
  MigrationIcon,
  MinusCircleFillIcon,
  MinusCircleIcon,
  MinusIcon,
  MobileFillIcon,
  MobileIcon,
  MobileSmallFillIcon,
  MobileSmallIcon,
  MobileTriangleFillIcon,
  MobileTriangleIcon,
  MonitorFillIcon,
  MonitorIcon,
  MonitorTriangleFillIcon,
  MonitorTriangleIcon,
  MoonFillIcon,
  MoonIcon,
  MotorcycleFillIcon,
  MotorcycleIcon,
  MountainFillIcon,
  MountainIcon,
  MugFillIcon,
  MugIcon,
  MultiplyIcon,
  NewspaperFillIcon,
  NewspaperIcon,
  NoSmokingFillIcon,
  NoSmokingIcon,
  NokIcon,
  NotePencilDashIcon,
  NotePencilFillIcon,
  NotePencilIcon,
  NumberListIcon,
  OpenSourceFillIcon,
  OpenSourceIcon,
  Over18FillIcon,
  Over18Icon,
  PackageFillIcon,
  PackageIcon,
  PadlockLockedFillIcon,
  PadlockLockedIcon,
  PadlockUnlockedFillIcon,
  PadlockUnlockedIcon,
  PaletteFillIcon,
  PaletteIcon,
  PaperclipIcon,
  PaperplaneFillIcon,
  PaperplaneIcon,
  ParagraphIcon,
  ParasolBeachFillIcon,
  ParasolBeachIcon,
  ParkingFillIcon,
  ParkingIcon,
  PassportFillIcon,
  PassportIcon,
  PasswordHiddenIcon,
  PauseFillIcon,
  PauseIcon,
  PencilBoardFillIcon,
  PencilBoardIcon,
  PencilFillIcon,
  PencilIcon,
  PencilLineFillIcon,
  PencilLineIcon,
  PencilWritingFillIcon,
  PencilWritingIcon,
  PentagonFillIcon,
  PentagonIcon,
  PercentIcon,
  PersonChatFillIcon,
  PersonChatIcon,
  PersonCheckmarkFillIcon,
  PersonCheckmarkIcon,
  PersonCircleFillIcon,
  PersonCircleIcon,
  PersonCrossFillIcon,
  PersonCrossIcon,
  PersonEnvelopeFillIcon,
  PersonEnvelopeIcon,
  PersonFillIcon,
  PersonGavelFillIcon,
  PersonGavelIcon,
  PersonGroupFillIcon,
  PersonGroupIcon,
  PersonHeadsetFillIcon,
  PersonHeadsetIcon,
  PersonIcon,
  PersonMinusFillIcon,
  PersonMinusIcon,
  PersonPencilFillIcon,
  PersonPencilIcon,
  PersonPlusFillIcon,
  PersonPlusIcon,
  PersonPregnantFillIcon,
  PersonPregnantIcon,
  PersonRectangleFillIcon,
  PersonRectangleIcon,
  PersonSuitFillIcon,
  PersonSuitIcon,
  PersonTallShortFillIcon,
  PersonTallShortIcon,
  PhoneFillIcon,
  PhoneIcon,
  PieChartFillIcon,
  PieChartIcon,
  PiggybankFillIcon,
  PiggybankIcon,
  PillCircleFillIcon,
  PillCircleIcon,
  PillCircleRectangleFillIcon,
  PillCircleRectangleIcon,
  PillRectangleFillIcon,
  PillRectangleIcon,
  PinFillIcon,
  PinIcon,
  PlantFillIcon,
  PlantIcon,
  PlateFillIcon,
  PlateIcon,
  PlayFillIcon,
  PlayIcon,
  PlusCircleFillIcon,
  PlusCircleIcon,
  PlusIcon,
  PlusMinusSlashIcon,
  PortalFillIcon,
  PortalIcon,
  PresentationFillIcon,
  PresentationIcon,
  PrinterLargeFillIcon,
  PrinterLargeIcon,
  PrinterLargeTriangleFillIcon,
  PrinterLargeTriangleIcon,
  PrinterSmallFillIcon,
  PrinterSmallIcon,
  PrinterSmallTriangleFillIcon,
  PrinterSmallTriangleIcon,
  PushPinFillIcon,
  PushPinIcon,
  PuzzlePieceFillIcon,
  PuzzlePieceIcon,
  QrCodeFillIcon,
  QrCodeIcon,
  QrCodeScanningFillIcon,
  QrCodeScanningIcon,
  QuestionmarkDiamondFillIcon,
  QuestionmarkDiamondIcon,
  QuestionmarkIcon,
  QuietZoneFillIcon,
  QuietZoneIcon,
  RaindropFillIcon,
  RaindropIcon,
  ReceiptFillIcon,
  ReceiptIcon,
  ReceptionFillIcon,
  ReceptionIcon,
  RecordFillIcon,
  RecordIcon,
  RectangleSectionsFillIcon,
  RectangleSectionsIcon,
  RecycleFillIcon,
  RecycleIcon,
  RefrigeratorFillIcon,
  RefrigeratorIcon,
  RoadblockFillIcon,
  RoadblockIcon,
  RobotFillIcon,
  RobotFrownFillIcon,
  RobotFrownIcon,
  RobotIcon,
  RobotSmileFillIcon,
  RobotSmileIcon,
  RocketFillIcon,
  RocketIcon,
  RockingHorseFillIcon,
  RockingHorseIcon,
  RotateLeftFillIcon,
  RotateLeftIcon,
  RotateRightFillIcon,
  RotateRightIcon,
  RouterIcon,
  RulerFillIcon,
  RulerIcon,
  RulersFillIcon,
  RulersIcon,
  SackFillIcon,
  SackIcon,
  SackKronerFillIcon,
  SackKronerIcon,
  SackPensionFillIcon,
  SackPensionIcon,
  SandboxFillIcon,
  SandboxIcon,
  ScissorsFillIcon,
  ScissorsIcon,
  SealCheckmarkFillIcon,
  SealCheckmarkIcon,
  SealFillIcon,
  SealIcon,
  SealXMarkFillIcon,
  SealXMarkIcon,
  SectorChartFillIcon,
  SectorChartIcon,
  ShieldFillIcon,
  ShieldIcon,
  ShieldLockFillIcon,
  ShieldLockIcon,
  ShoppingBasketFillIcon,
  ShoppingBasketIcon,
  ShowerFillIcon,
  ShowerIcon,
  ShrinkIcon,
  SidebarBothFillIcon,
  SidebarBothIcon,
  SidebarLeftFillIcon,
  SidebarLeftIcon,
  SidebarRightFillIcon,
  SidebarRightIcon,
  SignLanguageSingleHandFillIcon,
  SignLanguageSingleHandIcon,
  SignLanguageTwoHandsFillIcon,
  SignLanguageTwoHandsIcon,
  SilhouetteFillIcon,
  SilhouetteIcon,
  SkipBackwardFillIcon,
  SkipBackwardIcon,
  SkipForwardFillIcon,
  SkipForwardIcon,
  SnowIcon,
  SparkLargeIcon,
  SparkSmallIcon,
  SparklesFillIcon,
  SparklesIcon,
  SpeakerFillIcon,
  SpeakerIcon,
  SpeakerSlashFillIcon,
  SpeakerSlashIcon,
  SpeakerSoundWave1FillIcon,
  SpeakerSoundWave1Icon,
  SpeakerSoundWave2FillIcon,
  SpeakerSoundWave2Icon,
  SpeakerSoundWave3FillIcon,
  SpeakerSoundWave3Icon,
  SplitHorizontalFillIcon,
  SplitHorizontalIcon,
  SplitVerticalFillIcon,
  SplitVerticalIcon,
  SpoonFillIcon,
  SpoonIcon,
  SquareFillIcon,
  SquareIcon,
  SquarerootIcon,
  StaircaseIcon,
  StarFillIcon,
  StarIcon,
  StarOfLifeFillIcon,
  StarOfLifeIcon,
  StarsEuIcon,
  StethoscopeIcon,
  StopFillIcon,
  StopIcon,
  StrollerFillIcon,
  StrollerIcon,
  SunFillIcon,
  SunIcon,
  TableFillIcon,
  TableIcon,
  TabletFillIcon,
  TabletIcon,
  TabsAddFillIcon,
  TabsAddIcon,
  TabsFillIcon,
  TabsIcon,
  TabsRemoveFillIcon,
  TabsRemoveIcon,
  TagFillIcon,
  TagIcon,
  TapWaterFillIcon,
  TapWaterIcon,
  TasklistFillIcon,
  TasklistIcon,
  TasklistSaveFillIcon,
  TasklistSaveIcon,
  TasklistSendFillIcon,
  TasklistSendIcon,
  TasklistStartFillIcon,
  TasklistStartIcon,
  TeddyBearFillIcon,
  TeddyBearIcon,
  TenancyFillIcon,
  TenancyIcon,
  TerminalFillIcon,
  TerminalIcon,
  TestFlaskFillIcon,
  TestFlaskIcon,
  ThermometerFillIcon,
  ThermometerIcon,
  ThumbDownFillIcon,
  ThumbDownIcon,
  ThumbUpFillIcon,
  ThumbUpIcon,
  TimerFillIcon,
  TimerIcon,
  TimerPauseFillIcon,
  TimerPauseIcon,
  TimerStartFillIcon,
  TimerStartIcon,
  ToiletFillIcon,
  ToiletIcon,
  TokenFillIcon,
  TokenIcon,
  ToothFillIcon,
  ToothIcon,
  TrainFillIcon,
  TrainIcon,
  TramFillIcon,
  TramIcon,
  TrashFillIcon,
  TrashIcon,
  TrayFoodFillIcon,
  TrayFoodIcon,
  TrendDownIcon,
  TrendFlatIcon,
  TrendUpIcon,
  TriangleFillIcon,
  TriangleIcon,
  TruckFillIcon,
  TruckIcon,
  UmbrellaFillIcon,
  UmbrellaIcon,
  UploadIcon,
  VideoFillIcon,
  VideoIcon,
  VideoSlashFillIcon,
  VideoSlashIcon,
  VideoplayerFillIcon,
  VideoplayerIcon,
  VirusFillIcon,
  VirusIcon,
  VitalsIcon,
  WaitingRoomFillIcon,
  WaitingRoomIcon,
  WalletFillIcon,
  WalletIcon,
  WateringCanFillIcon,
  WateringCanIcon,
  WaveformIcon,
  WavesIcon,
  WeightIcon,
  WheelchairFillIcon,
  WheelchairIcon,
  WrenchFillIcon,
  WrenchIcon,
  XMarkIcon,
  XMarkOctagonFillIcon,
  XMarkOctagonIcon,
  ZoomMinusFillIcon,
  ZoomMinusIcon,
  ZoomPlusFillIcon,
  ZoomPlusIcon,
} from "@navikt/aksel-icons";


export interface IconsMap {
  [key: string]: JSX.Element | { outline: JSX.Element; solid: JSX.Element };
}

export type IconName = keyof typeof iconsMap;

export const iconsMap = {
  airplane: { solid: <AirplaneFillIcon />, outline: <AirplaneIcon /> },
  "align-bottom": {
    solid: <AlignBottomFillIcon />,
    outline: <AlignBottomIcon />,
  },
  "align-center": {
    solid: <AlignCenterFillIcon />,
    outline: <AlignCenterIcon />,
  },
  "align-left": {
    solid: <AlignLeftFillIcon />,
    outline: <AlignLeftIcon />,
  },
  "align-middle": {
    solid: <AlignMiddleFillIcon />,
    outline: <AlignMiddleIcon />,
  },
  "align-right": {
    solid: <AlignRightFillIcon />,
    outline: <AlignRightIcon />,
  },
  "align-top": { solid: <AlignTopFillIcon />, outline: <AlignTopIcon /> },
  allergens: { solid: <AllergensFillIcon />, outline: <AllergensIcon /> },
  angle: { outline: <AngleIcon /> },
  "angle-ruler-circle": {
    solid: <AngleRulerCircleFillIcon />,
    outline: <AngleRulerCircleIcon />,
  },
  "angle-ruler-triangle": {
    solid: <AngleRulerTriangleFillIcon />,
    outline: <AngleRulerTriangleIcon />,
  },
  archive: { solid: <ArchiveFillIcon />, outline: <ArchiveIcon /> },
  "area-chart": {
    solid: <AreaChartFillIcon />,
    outline: <AreaChartIcon />,
  },
  "arrow-circlepath": { outline: <ArrowCirclepathIcon /> },
  "arrow-down": { outline: <ArrowDownIcon /> },
  "arrow-down-right": { outline: <ArrowDownRightIcon /> },
  "arrow-forward": {
    solid: <ArrowForwardFillIcon />,
    outline: <ArrowForwardIcon />,
  },
  "arrow-left": { outline: <ArrowLeftIcon /> },
  "arrow-redo": { outline: <ArrowRedoIcon /> },
  "arrow-right": { outline: <ArrowRightIcon /> },
  "arrow-right-left": { outline: <ArrowRightLeftIcon /> },
  "arrow-undo": { outline: <ArrowUndoIcon /> },
  "arrow-up": { outline: <ArrowUpIcon /> },
  "arrows-circlepath": { outline: <ArrowsCirclepathIcon /> },
  "arrows-squarepath": { outline: <ArrowsSquarepathIcon /> },
  "arrows-up-down": { outline: <ArrowsUpDownIcon /> },
  "baby-wrapped": {
    solid: <BabyWrappedFillIcon />,
    outline: <BabyWrappedIcon />,
  },
  backpack: { solid: <BackpackFillIcon />, outline: <BackpackIcon /> },
  backward: { solid: <BackwardFillIcon />, outline: <BackwardIcon /> },
  bacteria: { solid: <BacteriaFillIcon />, outline: <BacteriaIcon /> },
  bagde: { solid: <BagdeFillIcon />, outline: <BagdeIcon /> },
  baggage: { solid: <BaggageFillIcon />, outline: <BaggageIcon /> },
  bandage: { solid: <BandageFillIcon />, outline: <BandageIcon /> },
  "bank-note": { solid: <BankNoteFillIcon />, outline: <BankNoteIcon /> },
  "bar-chart": { solid: <BarChartFillIcon />, outline: <BarChartIcon /> },
  bed: { solid: <BedFillIcon />, outline: <BedIcon /> },
  "bell-dot": { solid: <BellDotFillIcon />, outline: <BellDotIcon /> },
  bell: { solid: <BellFillIcon />, outline: <BellIcon /> },
  bicycle: { outline: <BicycleIcon /> },
  boat: { solid: <BoatFillIcon />, outline: <BoatIcon /> },
  "bone-broken": { outline: <BoneBrokenIcon /> },
  bone: { solid: <BoneFillIcon />, outline: <BoneIcon /> },
  book: { solid: <BookFillIcon />, outline: <BookIcon /> },
  "bookmark-dash": { outline: <BookmarkDashIcon /> },
  bookmark: { solid: <BookmarkFillIcon />, outline: <BookmarkIcon /> },
  books: { solid: <BooksFillIcon />, outline: <BooksIcon /> },
  bowl: { solid: <BowlFillIcon />, outline: <BowlIcon /> },
  braille: { solid: <BrailleFillIcon />, outline: <BrailleIcon /> },
  branching: { outline: <BranchingIcon /> },
  "briefcase-clock": {
    solid: <BriefcaseClockFillIcon />,
    outline: <BriefcaseClockIcon />,
  },
  briefcase: { solid: <BriefcaseFillIcon />, outline: <BriefcaseIcon /> },
  broadcast: { outline: <BroadcastIcon /> },
  "broadcast-minus-circle": {
    solid: <BroadcastMinusCircleFillIcon />,
    outline: <BroadcastMinusCircleIcon />,
  },
  "broadcast-plus-circle": {
    solid: <BroadcastPlusCircleFillIcon />,
    outline: <BroadcastPlusCircleIcon />,
  },
  "bubble-chart": {
    solid: <BubbleChartFillIcon />,
    outline: <BubbleChartIcon />,
  },
  bucket: { solid: <BucketFillIcon />, outline: <BucketIcon /> },
  "bucket-mop": {
    solid: <BucketMopFillIcon />,
    outline: <BucketMopIcon />,
  },
  bug: { solid: <BugFillIcon />, outline: <BugIcon /> },
  buildings2: {
    solid: <Buildings2FillIcon />,
    outline: <Buildings2Icon />,
  },
  buildings3: {
    solid: <Buildings3FillIcon />,
    outline: <Buildings3Icon />,
  },
  "bullet-list": { outline: <BulletListIcon /> },
  bus: { solid: <BusFillIcon />, outline: <BusIcon /> },
  calculator: {
    solid: <CalculatorFillIcon />,
    outline: <CalculatorIcon />,
  },
  calendar: { solid: <CalendarFillIcon />, outline: <CalendarIcon /> },
  camera: { solid: <CameraFillIcon />, outline: <CameraIcon /> },
  "camera-triangle": {
    solid: <CameraTriangleFillIcon />,
    outline: <CameraTriangleIcon />,
  },
  candle: { solid: <CandleFillIcon />, outline: <CandleIcon /> },
  captions: { solid: <CaptionsFillIcon />, outline: <CaptionsIcon /> },
  car: { solid: <CarFillIcon />, outline: <CarIcon /> },
  card: { solid: <CardFillIcon />, outline: <CardIcon /> },
  "caret-down-circle": {
    solid: <CaretDownCircleFillIcon />,
    outline: <CaretDownCircleIcon />,
  },
  "caret-down": {
    solid: <CaretDownFillIcon />,
    outline: <CaretDownIcon />,
  },
  "caret-left-circle": {
    solid: <CaretLeftCircleFillIcon />,
    outline: <CaretLeftCircleIcon />,
  },
  "caret-left": {
    solid: <CaretLeftFillIcon />,
    outline: <CaretLeftIcon />,
  },
  "caret-left-right": {
    solid: <CaretLeftRightFillIcon />,
    outline: <CaretLeftRightIcon />,
  },
  "caret-right-circle": {
    solid: <CaretRightCircleFillIcon />,
    outline: <CaretRightCircleIcon />,
  },
  "caret-right": {
    solid: <CaretRightFillIcon />,
    outline: <CaretRightIcon />,
  },
  "caret-up-circle": {
    solid: <CaretUpCircleFillIcon />,
    outline: <CaretUpCircleIcon />,
  },
  "caret-up-down": {
    solid: <CaretUpDownFillIcon />,
    outline: <CaretUpDownIcon />,
  },
  "caret-up-down-filled-down": { outline: <CaretUpDownFilledDownIcon /> },
  "caret-up-down-filled-up": { outline: <CaretUpDownFilledUpIcon /> },
  "caret-up": { solid: <CaretUpFillIcon />, outline: <CaretUpIcon /> },
  "changing-room": {
    solid: <ChangingRoomFillIcon />,
    outline: <ChangingRoomIcon />,
  },
  chat2: { solid: <Chat2FillIcon />, outline: <Chat2Icon /> },
  "chat-checkmark": {
    solid: <ChatCheckmarkFillIcon />,
    outline: <ChatCheckmarkIcon />,
  },
  "chat-elipsis": {
    solid: <ChatElipsisFillIcon />,
    outline: <ChatElipsisIcon />,
  },
  "chat-exclamationmark": {
    solid: <ChatExclamationmarkFillIcon />,
    outline: <ChatExclamationmarkIcon />,
  },
  chat: { solid: <ChatFillIcon />, outline: <ChatIcon /> },
  "checkmark-circle": {
    solid: <CheckmarkCircleFillIcon />,
    outline: <CheckmarkCircleIcon />,
  },
  checkmark: { outline: <CheckmarkIcon /> },
  "chef-hat": { solid: <ChefHatFillIcon />, outline: <ChefHatIcon /> },
  "chevron-down-circle": {
    solid: <ChevronDownCircleFillIcon />,
    outline: <ChevronDownCircleIcon />,
  },
  "chevron-down-double-circle": {
    solid: <ChevronDownDoubleCircleFillIcon />,
    outline: <ChevronDownDoubleCircleIcon />,
  },
  "chevron-down-double": { outline: <ChevronDownDoubleIcon /> },
  "chevron-down": { outline: <ChevronDownIcon /> },
  "chevron-down-up": { outline: <ChevronDownUpIcon /> },
  "chevron-left-circle": {
    solid: <ChevronLeftCircleFillIcon />,
    outline: <ChevronLeftCircleIcon />,
  },
  "chevron-left-double-circle": {
    solid: <ChevronLeftDoubleCircleFillIcon />,
    outline: <ChevronLeftDoubleCircleIcon />,
  },
  "chevron-left-double": { outline: <ChevronLeftDoubleIcon /> },
  "chevron-left-first-circle": {
    solid: <ChevronLeftFirstCircleFillIcon />,
    outline: <ChevronLeftFirstCircleIcon />,
  },
  "chevron-left-first": { outline: <ChevronLeftFirstIcon /> },
  "chevron-left": { outline: <ChevronLeftIcon /> },
  "chevron-right-circle": {
    solid: <ChevronRightCircleFillIcon />,
    outline: <ChevronRightCircleIcon />,
  },
  "chevron-right-double-circle": {
    solid: <ChevronRightDoubleCircleFillIcon />,
    outline: <ChevronRightDoubleCircleIcon />,
  },
  "chevron-right-double": { outline: <ChevronRightDoubleIcon /> },
  "chevron-right": { outline: <ChevronRightIcon /> },
  "chevron-right-last-circle": {
    solid: <ChevronRightLastCircleFillIcon />,
    outline: <ChevronRightLastCircleIcon />,
  },
  "chevron-right-last": { outline: <ChevronRightLastIcon /> },
  "chevron-up-circle": {
    solid: <ChevronUpCircleFillIcon />,
    outline: <ChevronUpCircleIcon />,
  },
  "chevron-up-double-circle": {
    solid: <ChevronUpDoubleCircleFillIcon />,
    outline: <ChevronUpDoubleCircleIcon />,
  },
  "chevron-up-double": { outline: <ChevronUpDoubleIcon /> },
  "chevron-up-down": { outline: <ChevronUpDownIcon /> },
  "chevron-up": { outline: <ChevronUpIcon /> },
  "child-eyes": {
    solid: <ChildEyesFillIcon />,
    outline: <ChildEyesIcon />,
  },
  "child-hair-eyes": {
    solid: <ChildHairEyesFillIcon />,
    outline: <ChildHairEyesIcon />,
  },
  cigarette: { solid: <CigaretteFillIcon />, outline: <CigaretteIcon /> },
  "circle-broken": { outline: <CircleBrokenIcon /> },
  circle: { solid: <CircleFillIcon />, outline: <CircleIcon /> },
  "circle-slash": {
    solid: <CircleSlashFillIcon />,
    outline: <CircleSlashIcon />,
  },
  "clipboard-checkmark": {
    solid: <ClipboardCheckmarkFillIcon />,
    outline: <ClipboardCheckmarkIcon />,
  },
  clipboard: { solid: <ClipboardFillIcon />, outline: <ClipboardIcon /> },
  "clipboard-link": {
    solid: <ClipboardLinkFillIcon />,
    outline: <ClipboardLinkIcon />,
  },
  "clipboard-x-mark": {
    solid: <ClipboardXMarkFillIcon />,
    outline: <ClipboardXMarkIcon />,
  },
  "clock-dashed": { outline: <ClockDashedIcon /> },
  clock: { solid: <ClockFillIcon />, outline: <ClockIcon /> },
  "clothing-hanger": {
    solid: <ClothingHangerFillIcon />,
    outline: <ClothingHangerIcon />,
  },
  "cloud-down": {
    solid: <CloudDownFillIcon />,
    outline: <CloudDownIcon />,
  },
  cloud: { solid: <CloudFillIcon />, outline: <CloudIcon /> },
  "cloud-slash": {
    solid: <CloudSlashFillIcon />,
    outline: <CloudSlashIcon />,
  },
  "cloud-up": { solid: <CloudUpFillIcon />, outline: <CloudUpIcon /> },
  code: { outline: <CodeIcon /> },
  coffee: { solid: <CoffeeFillIcon />, outline: <CoffeeIcon /> },
  cog: { solid: <CogFillIcon />, outline: <CogIcon /> },
  "cog-rotation": {
    solid: <CogRotationFillIcon />,
    outline: <CogRotationIcon />,
  },
  combifridge1: {
    solid: <Combifridge1FillIcon />,
    outline: <Combifridge1Icon />,
  },
  combifridge2: {
    solid: <Combifridge2FillIcon />,
    outline: <Combifridge2Icon />,
  },
  compass: { solid: <CompassFillIcon />, outline: <CompassIcon /> },
  component: { solid: <ComponentFillIcon />, outline: <ComponentIcon /> },
  "currency-exchange": { outline: <CurrencyExchangeIcon /> },
  cutlery: { solid: <CutleryFillIcon />, outline: <CutleryIcon /> },
  database: { solid: <DatabaseFillIcon />, outline: <DatabaseIcon /> },
  density1: { solid: <Density1FillIcon />, outline: <Density1Icon /> },
  density2: { solid: <Density2FillIcon />, outline: <Density2Icon /> },
  density3: { outline: <Density3Icon /> },
  diamond: { solid: <DiamondFillIcon />, outline: <DiamondIcon /> },
  dishwasher: {
    solid: <DishwasherFillIcon />,
    outline: <DishwasherIcon />,
  },
  divide: { outline: <DivideIcon /> },
  "doc-pencil": {
    solid: <DocPencilFillIcon />,
    outline: <DocPencilIcon />,
  },
  dog: { solid: <DogFillIcon />, outline: <DogIcon /> },
  "dog-harness": {
    solid: <DogHarnessFillIcon />,
    outline: <DogHarnessIcon />,
  },
  "donut-chart": {
    solid: <DonutChartFillIcon />,
    outline: <DonutChartIcon />,
  },
  donuts: { solid: <DonutsFillIcon />, outline: <DonutsIcon /> },
  door: { solid: <DoorFillIcon />, outline: <DoorIcon /> },
  "door-open": { solid: <DoorOpenFillIcon />, outline: <DoorOpenIcon /> },
  download: { outline: <DownloadIcon /> },
  "drag-horizontal": { outline: <DragHorizontalIcon /> },
  "drag-vertical": { outline: <DragVerticalIcon /> },
  ear: { solid: <EarFillIcon />, outline: <EarIcon /> },
  "ear-slash": { solid: <EarSlashFillIcon />, outline: <EarSlashIcon /> },
  "ear-soundwaves": {
    solid: <EarSoundwavesFillIcon />,
    outline: <EarSoundwavesIcon />,
  },
  earth: { solid: <EarthFillIcon />, outline: <EarthIcon /> },
  elevator: { solid: <ElevatorFillIcon />, outline: <ElevatorIcon /> },
  enter: { outline: <EnterIcon /> },
  "envelope-closed": {
    solid: <EnvelopeClosedFillIcon />,
    outline: <EnvelopeClosedIcon />,
  },
  "envelope-open": {
    solid: <EnvelopeOpenFillIcon />,
    outline: <EnvelopeOpenIcon />,
  },
  equals: { outline: <EqualsIcon /> },
  eraser: { solid: <EraserFillIcon />, outline: <EraserIcon /> },
  escalator: { outline: <EscalatorIcon /> },
  ethernet: { outline: <EthernetIcon /> },
  exclamationmark: { outline: <ExclamationmarkIcon /> },
  "exclamationmark-triangle": {
    solid: <ExclamationmarkTriangleFillIcon />,
    outline: <ExclamationmarkTriangleIcon />,
  },
  expand: { outline: <ExpandIcon /> },
  "external-link": {
    solid: <ExternalLinkFillIcon />,
    outline: <ExternalLinkIcon />,
  },
  "eye-closed": { outline: <EyeClosedIcon /> },
  eye: { solid: <EyeFillIcon />, outline: <EyeIcon /> },
  "eye-obfuscated": {
    solid: <EyeObfuscatedFillIcon />,
    outline: <EyeObfuscatedIcon />,
  },
  "eye-slash": { solid: <EyeSlashFillIcon />, outline: <EyeSlashIcon /> },
  "eye-with-pupil": {
    solid: <EyeWithPupilFillIcon />,
    outline: <EyeWithPupilIcon />,
  },
  "face-cry": { solid: <FaceCryFillIcon />, outline: <FaceCryIcon /> },
  face: { solid: <FaceFillIcon />, outline: <FaceIcon /> },
  "face-frown": {
    solid: <FaceFrownFillIcon />,
    outline: <FaceFrownIcon />,
  },
  "face-laugh": {
    solid: <FaceLaughFillIcon />,
    outline: <FaceLaughIcon />,
  },
  "face-smile": {
    solid: <FaceSmileFillIcon />,
    outline: <FaceSmileIcon />,
  },
  "feeding-bottle": {
    solid: <FeedingBottleFillIcon />,
    outline: <FeedingBottleIcon />,
  },
  "figure-child": {
    solid: <FigureChildFillIcon />,
    outline: <FigureChildIcon />,
  },
  "figure-combination": {
    solid: <FigureCombinationFillIcon />,
    outline: <FigureCombinationIcon />,
  },
  figure: { solid: <FigureFillIcon />, outline: <FigureIcon /> },
  "figure-inward": {
    solid: <FigureInwardFillIcon />,
    outline: <FigureInwardIcon />,
  },
  "figure-outward": {
    solid: <FigureOutwardFillIcon />,
    outline: <FigureOutwardIcon />,
  },
  "file-checkmark": {
    solid: <FileCheckmarkFillIcon />,
    outline: <FileCheckmarkIcon />,
  },
  "file-code": { solid: <FileCodeFillIcon />, outline: <FileCodeIcon /> },
  "file-csv": { solid: <FileCsvFillIcon />, outline: <FileCsvIcon /> },
  "file-excel": {
    solid: <FileExcelFillIcon />,
    outline: <FileExcelIcon />,
  },
  "file-export": {
    solid: <FileExportFillIcon />,
    outline: <FileExportIcon />,
  },
  file: { solid: <FileFillIcon />, outline: <FileIcon /> },
  "file-image": {
    solid: <FileImageFillIcon />,
    outline: <FileImageIcon />,
  },
  "file-import": {
    solid: <FileImportFillIcon />,
    outline: <FileImportIcon />,
  },
  "file-json": { solid: <FileJsonFillIcon />, outline: <FileJsonIcon /> },
  "file-loading": {
    solid: <FileLoadingFillIcon />,
    outline: <FileLoadingIcon />,
  },
  "file-paragraph": {
    solid: <FileParagraphFillIcon />,
    outline: <FileParagraphIcon />,
  },
  "file-pdf": { solid: <FilePdfFillIcon />, outline: <FilePdfIcon /> },
  "file-plus": { solid: <FilePlusFillIcon />, outline: <FilePlusIcon /> },
  "file-reset": {
    solid: <FileResetFillIcon />,
    outline: <FileResetIcon />,
  },
  "file-search": {
    solid: <FileSearchFillIcon />,
    outline: <FileSearchIcon />,
  },
  "file-shredder": {
    solid: <FileShredderFillIcon />,
    outline: <FileShredderIcon />,
  },
  "file-text": { solid: <FileTextFillIcon />, outline: <FileTextIcon /> },
  "file-word": { solid: <FileWordFillIcon />, outline: <FileWordIcon /> },
  "file-x-mark": {
    solid: <FileXMarkFillIcon />,
    outline: <FileXMarkIcon />,
  },
  files: { solid: <FilesFillIcon />, outline: <FilesIcon /> },
  filter: { outline: <FilterIcon /> },
  "finger-button": {
    solid: <FingerButtonFillIcon />,
    outline: <FingerButtonIcon />,
  },
  "finger-mobile": {
    solid: <FingerMobileFillIcon />,
    outline: <FingerMobileIcon />,
  },
  "first-aid": { solid: <FirstAidFillIcon />, outline: <FirstAidIcon /> },
  "first-aid-kit": {
    solid: <FirstAidKitFillIcon />,
    outline: <FirstAidKitIcon />,
  },
  "flag-cross": {
    solid: <FlagCrossFillIcon />,
    outline: <FlagCrossIcon />,
  },
  floppydisk: {
    solid: <FloppydiskFillIcon />,
    outline: <FloppydiskIcon />,
  },
  flower: { solid: <FlowerFillIcon />, outline: <FlowerIcon /> },
  "flower-pension": {
    solid: <FlowerPensionFillIcon />,
    outline: <FlowerPensionIcon />,
  },
  "flower-petal-falling": {
    solid: <FlowerPetalFallingFillIcon />,
    outline: <FlowerPetalFallingIcon />,
  },
  "flower-petals": {
    solid: <FlowerPetalsFillIcon />,
    outline: <FlowerPetalsIcon />,
  },
  "folder-file": {
    solid: <FolderFileFillIcon />,
    outline: <FolderFileIcon />,
  },
  folder: { solid: <FolderFillIcon />, outline: <FolderIcon /> },
  "folder-minus": {
    solid: <FolderMinusFillIcon />,
    outline: <FolderMinusIcon />,
  },
  "folder-plus": {
    solid: <FolderPlusFillIcon />,
    outline: <FolderPlusIcon />,
  },
  fork: { solid: <ForkFillIcon />, outline: <ForkIcon /> },
  forward: { solid: <ForwardFillIcon />, outline: <ForwardIcon /> },
  freezer: { solid: <FreezerFillIcon />, outline: <FreezerIcon /> },
  funnel: { solid: <FunnelFillIcon />, outline: <FunnelIcon /> },
  gavel: { solid: <GavelFillIcon />, outline: <GavelIcon /> },
  "gavel-sound-block": {
    solid: <GavelSoundBlockFillIcon />,
    outline: <GavelSoundBlockIcon />,
  },
  glass: { solid: <GlassFillIcon />, outline: <GlassIcon /> },
  glasses: { solid: <GlassesFillIcon />, outline: <GlassesIcon /> },
  globe: { solid: <GlobeFillIcon />, outline: <GlobeIcon /> },
  "globe-slash": {
    solid: <GlobeSlashFillIcon />,
    outline: <GlobeSlashIcon />,
  },
  "hand-bandage": {
    solid: <HandBandageFillIcon />,
    outline: <HandBandageIcon />,
  },
  "hand-finger": {
    solid: <HandFingerFillIcon />,
    outline: <HandFingerIcon />,
  },
  "hand-heart": {
    solid: <HandHeartFillIcon />,
    outline: <HandHeartIcon />,
  },
  "hand-knot-filled": { outline: <HandKnotFilledIcon /> },
  "hand-knot": { outline: <HandKnotIcon /> },
  "hand-shake-heart": {
    solid: <HandShakeHeartFillIcon />,
    outline: <HandShakeHeartIcon />,
  },
  handshake: { solid: <HandshakeFillIcon />, outline: <HandshakeIcon /> },
  hanger: { outline: <HangerIcon /> },
  "hard-hat": { solid: <HardHatFillIcon />, outline: <HardHatIcon /> },
  hashtag: { outline: <HashtagIcon /> },
  "hat-school": {
    solid: <HatSchoolFillIcon />,
    outline: <HatSchoolIcon />,
  },
  "hdd-down": { solid: <HddDownFillIcon />, outline: <HddDownIcon /> },
  "hdd-up": { solid: <HddUpFillIcon />, outline: <HddUpIcon /> },
  "head-cloud": {
    solid: <HeadCloudFillIcon />,
    outline: <HeadCloudIcon />,
  },
  head: { solid: <HeadFillIcon />, outline: <HeadIcon /> },
  "head-heart": {
    solid: <HeadHeartFillIcon />,
    outline: <HeadHeartIcon />,
  },
  "hearing-loop": {
    solid: <HearingLoopFillIcon />,
    outline: <HearingLoopIcon />,
  },
  "hearing-loop-radio": {
    solid: <HearingLoopRadioFillIcon />,
    outline: <HearingLoopRadioIcon />,
  },
  "heart-broken": {
    solid: <HeartBrokenFillIcon />,
    outline: <HeartBrokenIcon />,
  },
  heart: { solid: <HeartFillIcon />, outline: <HeartIcon /> },
  "hexagon-grid": {
    solid: <HexagonGridFillIcon />,
    outline: <HexagonGridIcon />,
  },
  "hiking-trail-sign": {
    solid: <HikingTrailSignFillIcon />,
    outline: <HikingTrailSignIcon />,
  },
  hospital: { solid: <HospitalFillIcon />, outline: <HospitalIcon /> },
  "hourglass-bottom-filled": { outline: <HourglassBottomFilledIcon /> },
  hourglass: { outline: <HourglassIcon /> },
  "hourglass-top-filled": { outline: <HourglassTopFilledIcon /> },
  house: { solid: <HouseFillIcon />, outline: <HouseIcon /> },
  "house-heart": {
    solid: <HouseHeartFillIcon />,
    outline: <HouseHeartIcon />,
  },
  image: { solid: <ImageFillIcon />, outline: <ImageIcon /> },
  "inbox-down": {
    solid: <InboxDownFillIcon />,
    outline: <InboxDownIcon />,
  },
  inbox: { solid: <InboxFillIcon />, outline: <InboxIcon /> },
  "inbox-up": { solid: <InboxUpFillIcon />, outline: <InboxUpIcon /> },
  information: { outline: <InformationIcon /> },
  "information-square": {
    solid: <InformationSquareFillIcon />,
    outline: <InformationSquareIcon />,
  },
  "iv-fluid-bag": {
    solid: <IvFluidBagFillIcon />,
    outline: <IvFluidBagIcon />,
  },
  "key-horizontal": {
    solid: <KeyHorizontalFillIcon />,
    outline: <KeyHorizontalIcon />,
  },
  "key-vertical": {
    solid: <KeyVerticalFillIcon />,
    outline: <KeyVerticalIcon />,
  },
  knife: { solid: <KnifeFillIcon />, outline: <KnifeIcon /> },
  kroner: { outline: <KronerIcon /> },
  language: { outline: <LanguageIcon /> },
  laptop: { solid: <LaptopFillIcon />, outline: <LaptopIcon /> },
  "laptop-triangle": {
    solid: <LaptopTriangleFillIcon />,
    outline: <LaptopTriangleIcon />,
  },
  "layer-minus": {
    solid: <LayerMinusFillIcon />,
    outline: <LayerMinusIcon />,
  },
  layers: { solid: <LayersFillIcon />, outline: <LayersIcon /> },
  "layers-plus": {
    solid: <LayersPlusFillIcon />,
    outline: <LayersPlusIcon />,
  },
  leave: { outline: <LeaveIcon /> },
  "light-bulb": {
    solid: <LightBulbFillIcon />,
    outline: <LightBulbIcon />,
  },
  lightning: { solid: <LightningFillIcon />, outline: <LightningIcon /> },
  "line-graph-dot": { outline: <LineGraphDotIcon /> },
  "line-graph": { outline: <LineGraphIcon /> },
  "line-graph-stacked": { outline: <LineGraphStackedIcon /> },
  "link-broken": { outline: <LinkBrokenIcon /> },
  link: { outline: <LinkIcon /> },
  "location-pin": {
    solid: <LocationPinFillIcon />,
    outline: <LocationPinIcon />,
  },
  "magnifying-glass": {
    solid: <MagnifyingGlassFillIcon />,
    outline: <MagnifyingGlassIcon />,
  },
  "measuring-tape": {
    solid: <MeasuringTapeFillIcon />,
    outline: <MeasuringTapeIcon />,
  },
  "medicine-bottle": {
    solid: <MedicineBottleFillIcon />,
    outline: <MedicineBottleIcon />,
  },
  "meeting-large": {
    solid: <MeetingLargeFillIcon />,
    outline: <MeetingLargeIcon />,
  },
  "meeting-small": {
    solid: <MeetingSmallFillIcon />,
    outline: <MeetingSmallIcon />,
  },
  megaphone: { solid: <MegaphoneFillIcon />, outline: <MegaphoneIcon /> },
  "megaphone-speaking": {
    solid: <MegaphoneSpeakingFillIcon />,
    outline: <MegaphoneSpeakingIcon />,
  },
  "menu-elipsis-horizontal-circle": {
    solid: <MenuElipsisHorizontalCircleFillIcon />,
    outline: <MenuElipsisHorizontalCircleIcon />,
  },
  "menu-elipsis-horizontal": { outline: <MenuElipsisHorizontalIcon /> },
  "menu-elipsis-horizontal-square": {
    solid: <MenuElipsisHorizontalSquareFillIcon />,
    outline: <MenuElipsisHorizontalSquareIcon />,
  },
  "menu-elipsis-vertical-circle": {
    solid: <MenuElipsisVerticalCircleFillIcon />,
    outline: <MenuElipsisVerticalCircleIcon />,
  },
  "menu-elipsis-vertical": { outline: <MenuElipsisVerticalIcon /> },
  "menu-elipsis-vertical-square": {
    solid: <MenuElipsisVerticalSquareFillIcon />,
    outline: <MenuElipsisVerticalSquareIcon />,
  },
  "menu-grid": { outline: <MenuGridIcon /> },
  "menu-hamburger": { outline: <MenuHamburgerIcon /> },
  microbe: { solid: <MicrobeFillIcon />, outline: <MicrobeIcon /> },
  microphone: {
    solid: <MicrophoneFillIcon />,
    outline: <MicrophoneIcon />,
  },
  "microphone-slash": {
    solid: <MicrophoneSlashFillIcon />,
    outline: <MicrophoneSlashIcon />,
  },
  migration: { outline: <MigrationIcon /> },
  "minus-circle": {
    solid: <MinusCircleFillIcon />,
    outline: <MinusCircleIcon />,
  },
  minus: { outline: <MinusIcon /> },
  mobile: { solid: <MobileFillIcon />, outline: <MobileIcon /> },
  "mobile-small": {
    solid: <MobileSmallFillIcon />,
    outline: <MobileSmallIcon />,
  },
  "mobile-triangle": {
    solid: <MobileTriangleFillIcon />,
    outline: <MobileTriangleIcon />,
  },
  monitor: { solid: <MonitorFillIcon />, outline: <MonitorIcon /> },
  "monitor-triangle": {
    solid: <MonitorTriangleFillIcon />,
    outline: <MonitorTriangleIcon />,
  },
  moon: { solid: <MoonFillIcon />, outline: <MoonIcon /> },
  motorcycle: {
    solid: <MotorcycleFillIcon />,
    outline: <MotorcycleIcon />,
  },
  mountain: { solid: <MountainFillIcon />, outline: <MountainIcon /> },
  mug: { solid: <MugFillIcon />, outline: <MugIcon /> },
  multiply: { outline: <MultiplyIcon /> },
  newspaper: { solid: <NewspaperFillIcon />, outline: <NewspaperIcon /> },
  "no-smoking": {
    solid: <NoSmokingFillIcon />,
    outline: <NoSmokingIcon />,
  },
  nok: { outline: <NokIcon /> },
  "note-pencil-dash": { outline: <NotePencilDashIcon /> },
  "note-pencil": {
    solid: <NotePencilFillIcon />,
    outline: <NotePencilIcon />,
  },
  "number-list": { outline: <NumberListIcon /> },
  "open-source": {
    solid: <OpenSourceFillIcon />,
    outline: <OpenSourceIcon />,
  },
  over18: { solid: <Over18FillIcon />, outline: <Over18Icon /> },
  package: { solid: <PackageFillIcon />, outline: <PackageIcon /> },
  "padlock-locked": {
    solid: <PadlockLockedFillIcon />,
    outline: <PadlockLockedIcon />,
  },
  "padlock-unlocked": {
    solid: <PadlockUnlockedFillIcon />,
    outline: <PadlockUnlockedIcon />,
  },
  palette: { solid: <PaletteFillIcon />, outline: <PaletteIcon /> },
  paperclip: { outline: <PaperclipIcon /> },
  paperplane: {
    solid: <PaperplaneFillIcon />,
    outline: <PaperplaneIcon />,
  },
  paragraph: { outline: <ParagraphIcon /> },
  "parasol-beach": {
    solid: <ParasolBeachFillIcon />,
    outline: <ParasolBeachIcon />,
  },
  parking: { solid: <ParkingFillIcon />, outline: <ParkingIcon /> },
  passport: { solid: <PassportFillIcon />, outline: <PassportIcon /> },
  "password-hidden": { outline: <PasswordHiddenIcon /> },
  pause: { solid: <PauseFillIcon />, outline: <PauseIcon /> },
  "pencil-board": {
    solid: <PencilBoardFillIcon />,
    outline: <PencilBoardIcon />,
  },
  pencil: { solid: <PencilFillIcon />, outline: <PencilIcon /> },
  "pencil-line": {
    solid: <PencilLineFillIcon />,
    outline: <PencilLineIcon />,
  },
  "pencil-writing": {
    solid: <PencilWritingFillIcon />,
    outline: <PencilWritingIcon />,
  },
  pentagon: { solid: <PentagonFillIcon />, outline: <PentagonIcon /> },
  percent: { outline: <PercentIcon /> },
  "person-chat": {
    solid: <PersonChatFillIcon />,
    outline: <PersonChatIcon />,
  },
  "person-checkmark": {
    solid: <PersonCheckmarkFillIcon />,
    outline: <PersonCheckmarkIcon />,
  },
  "person-circle": {
    solid: <PersonCircleFillIcon />,
    outline: <PersonCircleIcon />,
  },
  "person-cross": {
    solid: <PersonCrossFillIcon />,
    outline: <PersonCrossIcon />,
  },
  "person-envelope": {
    solid: <PersonEnvelopeFillIcon />,
    outline: <PersonEnvelopeIcon />,
  },
  person: { solid: <PersonFillIcon />, outline: <PersonIcon /> },
  "person-gavel": {
    solid: <PersonGavelFillIcon />,
    outline: <PersonGavelIcon />,
  },
  "person-group": {
    solid: <PersonGroupFillIcon />,
    outline: <PersonGroupIcon />,
  },
  "person-headset": {
    solid: <PersonHeadsetFillIcon />,
    outline: <PersonHeadsetIcon />,
  },
  "person-minus": {
    solid: <PersonMinusFillIcon />,
    outline: <PersonMinusIcon />,
  },
  "person-pencil": {
    solid: <PersonPencilFillIcon />,
    outline: <PersonPencilIcon />,
  },
  "person-plus": {
    solid: <PersonPlusFillIcon />,
    outline: <PersonPlusIcon />,
  },
  "person-pregnant": {
    solid: <PersonPregnantFillIcon />,
    outline: <PersonPregnantIcon />,
  },
  "person-rectangle": {
    solid: <PersonRectangleFillIcon />,
    outline: <PersonRectangleIcon />,
  },
  "person-suit": {
    solid: <PersonSuitFillIcon />,
    outline: <PersonSuitIcon />,
  },
  "person-tall-short": {
    solid: <PersonTallShortFillIcon />,
    outline: <PersonTallShortIcon />,
  },
  phone: { solid: <PhoneFillIcon />, outline: <PhoneIcon /> },
  "pie-chart": { solid: <PieChartFillIcon />, outline: <PieChartIcon /> },
  piggybank: { solid: <PiggybankFillIcon />, outline: <PiggybankIcon /> },
  "pill-circle": {
    solid: <PillCircleFillIcon />,
    outline: <PillCircleIcon />,
  },
  "pill-circle-rectangle": {
    solid: <PillCircleRectangleFillIcon />,
    outline: <PillCircleRectangleIcon />,
  },
  "pill-rectangle": {
    solid: <PillRectangleFillIcon />,
    outline: <PillRectangleIcon />,
  },
  pin: { solid: <PinFillIcon />, outline: <PinIcon /> },
  plant: { solid: <PlantFillIcon />, outline: <PlantIcon /> },
  plate: { solid: <PlateFillIcon />, outline: <PlateIcon /> },
  play: { solid: <PlayFillIcon />, outline: <PlayIcon /> },
  "plus-circle": {
    solid: <PlusCircleFillIcon />,
    outline: <PlusCircleIcon />,
  },
  plus: { outline: <PlusIcon /> },
  "plus-minus-slash": { outline: <PlusMinusSlashIcon /> },
  portal: { solid: <PortalFillIcon />, outline: <PortalIcon /> },
  presentation: {
    solid: <PresentationFillIcon />,
    outline: <PresentationIcon />,
  },
  "printer-large": {
    solid: <PrinterLargeFillIcon />,
    outline: <PrinterLargeIcon />,
  },
  "printer-large-triangle": {
    solid: <PrinterLargeTriangleFillIcon />,
    outline: <PrinterLargeTriangleIcon />,
  },
  "printer-small": {
    solid: <PrinterSmallFillIcon />,
    outline: <PrinterSmallIcon />,
  },
  "printer-small-triangle": {
    solid: <PrinterSmallTriangleFillIcon />,
    outline: <PrinterSmallTriangleIcon />,
  },
  "push-pin": { solid: <PushPinFillIcon />, outline: <PushPinIcon /> },
  "puzzle-piece": {
    solid: <PuzzlePieceFillIcon />,
    outline: <PuzzlePieceIcon />,
  },
  "qr-code": { solid: <QrCodeFillIcon />, outline: <QrCodeIcon /> },
  "qr-code-scanning": {
    solid: <QrCodeScanningFillIcon />,
    outline: <QrCodeScanningIcon />,
  },
  "questionmark-diamond": {
    solid: <QuestionmarkDiamondFillIcon />,
    outline: <QuestionmarkDiamondIcon />,
  },
  questionmark: { outline: <QuestionmarkIcon /> },
  "quiet-zone": {
    solid: <QuietZoneFillIcon />,
    outline: <QuietZoneIcon />,
  },
  raindrop: { solid: <RaindropFillIcon />, outline: <RaindropIcon /> },
  receipt: { solid: <ReceiptFillIcon />, outline: <ReceiptIcon /> },
  reception: { solid: <ReceptionFillIcon />, outline: <ReceptionIcon /> },
  record: { solid: <RecordFillIcon />, outline: <RecordIcon /> },
  "rectangle-sections": {
    solid: <RectangleSectionsFillIcon />,
    outline: <RectangleSectionsIcon />,
  },
  recycle: { solid: <RecycleFillIcon />, outline: <RecycleIcon /> },
  refrigerator: {
    solid: <RefrigeratorFillIcon />,
    outline: <RefrigeratorIcon />,
  },
  roadblock: { solid: <RoadblockFillIcon />, outline: <RoadblockIcon /> },
  robot: { solid: <RobotFillIcon />, outline: <RobotIcon /> },
  "robot-frown": {
    solid: <RobotFrownFillIcon />,
    outline: <RobotFrownIcon />,
  },
  "robot-smile": {
    solid: <RobotSmileFillIcon />,
    outline: <RobotSmileIcon />,
  },
  rocket: { solid: <RocketFillIcon />, outline: <RocketIcon /> },
  "rocking-horse": {
    solid: <RockingHorseFillIcon />,
    outline: <RockingHorseIcon />,
  },
  "rotate-left": {
    solid: <RotateLeftFillIcon />,
    outline: <RotateLeftIcon />,
  },
  "rotate-right": {
    solid: <RotateRightFillIcon />,
    outline: <RotateRightIcon />,
  },
  router: { outline: <RouterIcon /> },
  ruler: { solid: <RulerFillIcon />, outline: <RulerIcon /> },
  rulers: { solid: <RulersFillIcon />, outline: <RulersIcon /> },
  sack: { solid: <SackFillIcon />, outline: <SackIcon /> },
  "sack-kroner": {
    solid: <SackKronerFillIcon />,
    outline: <SackKronerIcon />,
  },
  "sack-pension": {
    solid: <SackPensionFillIcon />,
    outline: <SackPensionIcon />,
  },
  sandbox: { solid: <SandboxFillIcon />, outline: <SandboxIcon /> },
  scissors: { solid: <ScissorsFillIcon />, outline: <ScissorsIcon /> },
  "seal-checkmark": {
    solid: <SealCheckmarkFillIcon />,
    outline: <SealCheckmarkIcon />,
  },
  seal: { solid: <SealFillIcon />, outline: <SealIcon /> },
  "seal-x-mark": {
    solid: <SealXMarkFillIcon />,
    outline: <SealXMarkIcon />,
  },
  "sector-chart": {
    solid: <SectorChartFillIcon />,
    outline: <SectorChartIcon />,
  },
  shield: { solid: <ShieldFillIcon />, outline: <ShieldIcon /> },
  "shield-lock": {
    solid: <ShieldLockFillIcon />,
    outline: <ShieldLockIcon />,
  },
  "shopping-basket": {
    solid: <ShoppingBasketFillIcon />,
    outline: <ShoppingBasketIcon />,
  },
  shower: { solid: <ShowerFillIcon />, outline: <ShowerIcon /> },
  shrink: { outline: <ShrinkIcon /> },
  "sidebar-both": {
    solid: <SidebarBothFillIcon />,
    outline: <SidebarBothIcon />,
  },
  "sidebar-left": {
    solid: <SidebarLeftFillIcon />,
    outline: <SidebarLeftIcon />,
  },
  "sidebar-right": {
    solid: <SidebarRightFillIcon />,
    outline: <SidebarRightIcon />,
  },
  "sign-language-single-hand": {
    solid: <SignLanguageSingleHandFillIcon />,
    outline: <SignLanguageSingleHandIcon />,
  },
  "sign-language-two-hands": {
    solid: <SignLanguageTwoHandsFillIcon />,
    outline: <SignLanguageTwoHandsIcon />,
  },
  silhouette: {
    solid: <SilhouetteFillIcon />,
    outline: <SilhouetteIcon />,
  },
  "skip-backward": {
    solid: <SkipBackwardFillIcon />,
    outline: <SkipBackwardIcon />,
  },
  "skip-forward": {
    solid: <SkipForwardFillIcon />,
    outline: <SkipForwardIcon />,
  },
  snow: { outline: <SnowIcon /> },
  "spark-large": { outline: <SparkLargeIcon /> },
  "spark-small": { outline: <SparkSmallIcon /> },
  sparkles: { solid: <SparklesFillIcon />, outline: <SparklesIcon /> },
  speaker: { solid: <SpeakerFillIcon />, outline: <SpeakerIcon /> },
  "speaker-slash": {
    solid: <SpeakerSlashFillIcon />,
    outline: <SpeakerSlashIcon />,
  },
  "speaker-sound-wave1": {
    solid: <SpeakerSoundWave1FillIcon />,
    outline: <SpeakerSoundWave1Icon />,
  },
  "speaker-sound-wave2": {
    solid: <SpeakerSoundWave2FillIcon />,
    outline: <SpeakerSoundWave2Icon />,
  },
  "speaker-sound-wave3": {
    solid: <SpeakerSoundWave3FillIcon />,
    outline: <SpeakerSoundWave3Icon />,
  },
  "split-horizontal": {
    solid: <SplitHorizontalFillIcon />,
    outline: <SplitHorizontalIcon />,
  },
  "split-vertical": {
    solid: <SplitVerticalFillIcon />,
    outline: <SplitVerticalIcon />,
  },
  spoon: { solid: <SpoonFillIcon />, outline: <SpoonIcon /> },
  square: { solid: <SquareFillIcon />, outline: <SquareIcon /> },
  squareroot: { outline: <SquarerootIcon /> },
  staircase: { outline: <StaircaseIcon /> },
  star: { solid: <StarFillIcon />, outline: <StarIcon /> },
  "star-of-life": {
    solid: <StarOfLifeFillIcon />,
    outline: <StarOfLifeIcon />,
  },
  "stars-eu": { outline: <StarsEuIcon /> },
  stethoscope: { outline: <StethoscopeIcon /> },
  stop: { solid: <StopFillIcon />, outline: <StopIcon /> },
  stroller: { solid: <StrollerFillIcon />, outline: <StrollerIcon /> },
  sun: { solid: <SunFillIcon />, outline: <SunIcon /> },
  table: { solid: <TableFillIcon />, outline: <TableIcon /> },
  tablet: { solid: <TabletFillIcon />, outline: <TabletIcon /> },
  "tabs-add": { solid: <TabsAddFillIcon />, outline: <TabsAddIcon /> },
  tabs: { solid: <TabsFillIcon />, outline: <TabsIcon /> },
  "tabs-remove": {
    solid: <TabsRemoveFillIcon />,
    outline: <TabsRemoveIcon />,
  },
  tag: { solid: <TagFillIcon />, outline: <TagIcon /> },
  "tap-water": { solid: <TapWaterFillIcon />, outline: <TapWaterIcon /> },
  tasklist: { solid: <TasklistFillIcon />, outline: <TasklistIcon /> },
  "tasklist-save": {
    solid: <TasklistSaveFillIcon />,
    outline: <TasklistSaveIcon />,
  },
  "tasklist-send": {
    solid: <TasklistSendFillIcon />,
    outline: <TasklistSendIcon />,
  },
  "tasklist-start": {
    solid: <TasklistStartFillIcon />,
    outline: <TasklistStartIcon />,
  },
  "teddy-bear": {
    solid: <TeddyBearFillIcon />,
    outline: <TeddyBearIcon />,
  },
  tenancy: { solid: <TenancyFillIcon />, outline: <TenancyIcon /> },
  terminal: { solid: <TerminalFillIcon />, outline: <TerminalIcon /> },
  "test-flask": {
    solid: <TestFlaskFillIcon />,
    outline: <TestFlaskIcon />,
  },
  thermometer: {
    solid: <ThermometerFillIcon />,
    outline: <ThermometerIcon />,
  },
  "thumb-down": {
    solid: <ThumbDownFillIcon />,
    outline: <ThumbDownIcon />,
  },
  "thumb-up": { solid: <ThumbUpFillIcon />, outline: <ThumbUpIcon /> },
  timer: { solid: <TimerFillIcon />, outline: <TimerIcon /> },
  "timer-pause": {
    solid: <TimerPauseFillIcon />,
    outline: <TimerPauseIcon />,
  },
  "timer-start": {
    solid: <TimerStartFillIcon />,
    outline: <TimerStartIcon />,
  },
  toilet: { solid: <ToiletFillIcon />, outline: <ToiletIcon /> },
  token: { solid: <TokenFillIcon />, outline: <TokenIcon /> },
  tooth: { solid: <ToothFillIcon />, outline: <ToothIcon /> },
  train: { solid: <TrainFillIcon />, outline: <TrainIcon /> },
  tram: { solid: <TramFillIcon />, outline: <TramIcon /> },
  trash: { solid: <TrashFillIcon />, outline: <TrashIcon /> },
  "tray-food": { solid: <TrayFoodFillIcon />, outline: <TrayFoodIcon /> },
  "trend-down": { outline: <TrendDownIcon /> },
  "trend-flat": { outline: <TrendFlatIcon /> },
  "trend-up": { outline: <TrendUpIcon /> },
  triangle: { solid: <TriangleFillIcon />, outline: <TriangleIcon /> },
  truck: { solid: <TruckFillIcon />, outline: <TruckIcon /> },
  umbrella: { solid: <UmbrellaFillIcon />, outline: <UmbrellaIcon /> },
  upload: { outline: <UploadIcon /> },
  video: { solid: <VideoFillIcon />, outline: <VideoIcon /> },
  "video-slash": {
    solid: <VideoSlashFillIcon />,
    outline: <VideoSlashIcon />,
  },
  videoplayer: {
    solid: <VideoplayerFillIcon />,
    outline: <VideoplayerIcon />,
  },
  virus: { solid: <VirusFillIcon />, outline: <VirusIcon /> },
  vitals: { outline: <VitalsIcon /> },
  "waiting-room": {
    solid: <WaitingRoomFillIcon />,
    outline: <WaitingRoomIcon />,
  },
  wallet: { solid: <WalletFillIcon />, outline: <WalletIcon /> },
  "watering-can": {
    solid: <WateringCanFillIcon />,
    outline: <WateringCanIcon />,
  },
  waveform: { outline: <WaveformIcon /> },
  waves: { outline: <WavesIcon /> },
  weight: { outline: <WeightIcon /> },
  wheelchair: {
    solid: <WheelchairFillIcon />,
    outline: <WheelchairIcon />,
  },
  wrench: { solid: <WrenchFillIcon />, outline: <WrenchIcon /> },
  "x-mark": { outline: <XMarkIcon /> },
  "x-mark-octagon": {
    solid: <XMarkOctagonFillIcon />,
    outline: <XMarkOctagonIcon />,
  },
  "zoom-minus": {
    solid: <ZoomMinusFillIcon />,
    outline: <ZoomMinusIcon />,
  },
  "zoom-plus": { solid: <ZoomPlusFillIcon />, outline: <ZoomPlusIcon /> },
};
