export type Color =
  | 'inherit'
  | 'accent'
  | 'company'
  | 'person'
  | 'neutral'
  | 'success'
  | 'warning'
  | 'error'
  | 'danger'
  | 'info'
  | 'alert';
export type Theme =
  | 'transparent'
  | 'default'
  | 'subtle'
  | 'surface'
  | 'surface-default'
  | 'surface-hover'
  | 'surface-active'
  | 'border'
  | 'border-subtle'
  | 'border-default'
  | 'border-strong'
  | 'base'
  | 'base-default'
  | 'base-hover'
  | 'base-active';
