export {
  Avatar as DsAvatar,
  //   Button as DsButton,
  Badge as DsBadge,
  Breadcrumbs as DsBreadcrumbs,
  Spinner as DsSpinner,
  Skeleton as DsSkeleton,
  Link as DsLink,
  List as DsList,
  Label as DsLabel,
  Heading as DsHeading,
  Paragraph as DsParagraph,
  ValidationMessage as DsValidationMessage,
  Details as DsDetails,
  Select as DsSelect,
  Alert as DsAlert,
  Tag as DsTag,
  Chip as DsChip,
  Pagination as DsPagination,
  usePagination as useDsPagination,
  type PaginationProps as DsPaginationProps,
  SkipLink as DsSkipLink,
  Tooltip as DsTooltip,
  Field as DsField,
  Checkbox as DsCheckbox,
  Radio as DsRadio,
  Fieldset as DsFieldset,
  Switch as DsSwitch,
  Textfield as DsTextfield,
  Textarea as DsTextarea,
  Input as DsInput,
  Tabs as DsTabs,
  ToggleGroup as DsToggleGroup,
  Popover as DsPopover,
  Divider as DsDivider,
  Dialog as DsDialog,
  Dropdown as DsDropdown,
  Search as DsSearch,
  Card as DsCard,
  Combobox as DsCombobox,
  Table as DsTable,
  ErrorSummary as DsErrorSummary,
  // Suggestion as DsSuggestion,
  // MultiSuggestion as DsMultiSuggestion, 
} from "@digdir/designsystemet-react";